#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath:$PWD/docurated:$PWD/concourse:$PWD/docurated:$PWD/garden-runc-release
export PATH=$PWD/gopath/bin:$PWD/docurated/concourse-bin:$PWD/concourse/bin:$PWD/garden-runc-release:$PATH

FINAL_VERSION="$(cat $PWD/final-version/version)"

mkdir cli-artifacts
mv fly-rc/fly_* cli-artifacts

go get github.com/jteeuwen/go-bindata/go-bindata

./gopath/src/github.com/docurated/concourse-bin/scripts/build-linux

go-bindata -nomemcopy -pkg bindata -o gopath/src/github.com/docurated/concourse-bin/bindata/bindata.go cli-artifacts/... linux/...

# must be build with 'daemon' flag because of docker packages :|
go build \
  -tags daemon \
  -ldflags "-X main.Version=${FINAL_VERSION} -X github.com/concourse/atc/atccmd.Version=${FINAL_VERSION}" \
  -o binary/concourse_linux_amd64 \
  github.com/docurated/concourse-bin/cmd/concourse
